name: lab

executables:
  sql:
    dependencies:
      - bytestring
      - monad-logger
      - mtl
      - neat-interpolation
      - persistent-sqlite
      - persistent-template
      - resourcet
      - text
      - yaml
    main: Main
    source-dirs: sql
  pi:
    dependencies:
      - parallel
    main: Main
    source-dirs: pi

dependencies:
  - base
