name: lab

executables:
  sql:
    dependencies:
      - bytestring
      - monad-logger
      - mtl
      - neat-interpolation
      - persistent-sqlite
      - persistent-template
      - resourcet
      - text
      - yaml
    main: Main
    source-dirs: sql
  pi:
    dependencies:
      # - criterion
      - parallel
      - timeit
    main: Main
    source-dirs: pi

dependencies:
  - base

ghc-options: -threaded -with-rtsopts=-N
